import pytest

from extensions.booksearch.bookdata import BookData


@pytest.fixture()
def waqfeya_bookls1():
    yield [
        BookData(title="صحيح البخاري (ت: ابن أبي علفة)",
                 author_name="محمد بن إسماعيل بن إبراهيم البخاري أبو عبد الله",
                 link="https://archive.org/details/FP154296", site_link="http://waqfeya.com/book.php?bid=12247"),
        BookData(title="القول الفريد فوائد على كتاب التوحيد", author_name="زيد بن مسفر البحري",
                 link="https://archive.org/details/FP163674", site_link="http://waqfeya.com/book.php?bid=12218"),
        BookData(title="صحيح البخاري (ط. الأوقاف السعودية)",
                 author_name="محمد بن إسماعيل بن إبراهيم البخاري أبو عبد الله",
                 link="https://archive.org/details/FP34714", site_link="http://waqfeya.com/book.php?bid=12205"),
        BookData(title="أضواء السنة", author_name="عبد الله بن عبد العزيز بن محمد اللحيدان",
                 link="https://archive.org/details/FP160479", site_link="http://waqfeya.com/book.php?bid=12004"),
        BookData(title="المنهل الحديث في شرح الحديث", author_name="موسى شاهين لاشين",
                 link="https://archive.org/details/FP56908", site_link="http://waqfeya.com/book.php?bid=11864"),
        BookData(title="صحيح البخاري (الكتاب الصوتي)", author_name="محمد بن إسماعيل بن إبراهيم بن المغيرة البخاري",
                 link="https://archive.org/details/Sahih_Al-Bukhari_MP3",
                 site_link="http://waqfeya.com/book.php?bid=11726"),
        BookData(title="كتاب التوحيد وكتاب القول السديد في مقاصد التوحيد",
                 author_name="محمد بن عبد الوهاب - عبد الرحمن بن ناصر السعدي",
                 link="https://archive.org/details/FP26444", site_link="http://waqfeya.com/book.php?bid=11492"),
        BookData(title="الزيادات على الموضوعات ويسمى ذيل اللآلئ المصنوعة",
                 author_name="جلال الدين عبد الرحمن بن أبي بكر السيوطي",
                 link="https://archive.org/details/FP113273", site_link="http://waqfeya.com/book.php?bid=11336"),
        BookData(title="مجموع مؤلفات الشيخ العلامة عبد الرحمن بن ناصر السعدي (ط. الأوقاف القطرية)",
                 author_name="عبد الرحمن بن ناصر السعدي", link="https://archive.org/details/FP121941",
                 site_link="http://waqfeya.com/book.php?bid=11206"),
        BookData(title="المهذب من إحياء علوم الدين", author_name="صالح أحمد الشامي",
                 link="https://archive.org/details/FP9886", site_link="http://waqfeya.com/book.php?bid=10922"),
        BookData(title="المحلى بالآثار (ط. العلمية)", author_name="علي بن أحمد بن سعيد بن حزم الأندلسي أبو محمد",
                 link="https://archive.org/details/FP74771", site_link="http://waqfeya.com/book.php?bid=10863"),
        BookData(title="مشكل الحديث وبيانه", author_name="ابن فورك",
                 link="https://archive.org/details/mshabimshabi",
                 site_link="http://waqfeya.com/book.php?bid=10733"),
        BookData(title="التذكرة في الفقه الشافعي",
                 author_name="عمر بن علي بن أحمد بن محمد المصري ابن الملقن الشافعي",
                 link="https://archive.org/details/FP89691", site_link="http://waqfeya.com/book.php?bid=10622"),
        BookData(title="الموضوعات", author_name="عبد الرحمن بن علي بن محمد بن علي بن الجوزي أبو الفرج",
                 link="https://archive.org/details/FP15210", site_link="http://waqfeya.com/book.php?bid=10599"),
        BookData(title="السراج المنير في ترتيب أحاديث صحيح الجامع الصغير", author_name="عصام موسى هادي",
                 link="https://archive.org/details/FP99429", site_link="http://waqfeya.com/book.php?bid=9849")]


@pytest.fixture()
def waqfeya_bookls2():
    yield [
        BookData(title="شرح أبواب من صحيح البخاري ويليه شرح أبواب من جامع الترمذي", author_name="ابن رجب الحنبلي",
                 link="https://archive.org/details/FP171605", site_link="http://waqfeya.com/book.php?bid=12390"),
        BookData(title="مؤتمر الانتصار للصحيحين", author_name="مجموعة من المؤلفين",
                 link="https://archive.org/details/IntsahIntsahPDF",
                 site_link="http://waqfeya.com/book.php?bid=12262"),
        BookData(title="صحيح البخاري (ت: ابن أبي علفة)",
                 author_name="محمد بن إسماعيل بن إبراهيم البخاري أبو عبد الله",
                 link="https://archive.org/details/FP154296", site_link="http://waqfeya.com/book.php?bid=12247"),
        BookData(title="صحيح البخاري (ط. الأوقاف السعودية)",
                 author_name="محمد بن إسماعيل بن إبراهيم البخاري أبو عبد الله",
                 link="https://archive.org/details/FP34714", site_link="http://waqfeya.com/book.php?bid=12205"),
        BookData(title="البحر الذي زخر في شرح ألفية الأثر", author_name="جلال الدين السيوطي",
                 link="https://archive.org/details/FP61983", site_link="http://waqfeya.com/book.php?bid=12089"),
        BookData(title="فتاوى اللجنة الدائمة للبحوث العلمية والإفتاء (المجموعة الثانية)",
                 author_name="اللجنة الدائمة للبحوث العلمية والإفتاء", link="https://archive.org/details/FP168880",
                 site_link="http://waqfeya.com/book.php?bid=12056"),
        BookData(
            title="صحيح البخاري الجامع المسند الصحيح المختصر من أمور رسول الله صلى الله عليه وسلم مع حاشية السهارنفوري وحاشية السندي (ط. البشرى)",
            author_name="محمد بن إسماعيل بن إبراهيم البخاري أبو عبد الله",
            link="https://archive.org/details/FP163611", site_link="http://waqfeya.com/book.php?bid=11909"),
        BookData(title="الحلل الإبريزية من التعليقات البازية على صحيح البخاري",
                 author_name="عبد العزيز بن عبد الله بن باز - عبد الله بن مانع الروقي أبو محمد",
                 link="https://archive.org/details/FP79821", site_link="http://waqfeya.com/book.php?bid=11868"),
        BookData(title="المجالس الوعظية في شرح أحاديث خير البرية صلى الله عليه وسلم من صحيح الإمام البخاري",
                 author_name="محمد بن عمر بن أحمد السفيري الشافعي", link="https://archive.org/details/FP74768",
                 site_link="http://waqfeya.com/book.php?bid=11867"),
        BookData(title="أزمة البخاري", author_name="معتز عبد الرحمن", link="https://archive.org/details/azmbukPDF",
                 site_link="http://waqfeya.com/book.php?bid=11797"),
        BookData(title="صحيح البخاري (الكتاب الصوتي)", author_name="محمد بن إسماعيل بن إبراهيم بن المغيرة البخاري",
                 link="https://archive.org/details/Sahih_Al-Bukhari_MP3",
                 site_link="http://waqfeya.com/book.php?bid=11726"),
        BookData(title="موسوعة الأعمال الكاملة للإمام محمد الخضر حسين", author_name="محمد الخضر حسين",
                 link="https://archive.org/details/FP125181", site_link="http://waqfeya.com/book.php?bid=11688"),
        BookData(title="صحيح البخاري (ط. العامرة - تركيا)", author_name="محمد بن إسماعيل البخاري",
                 link="https://archive.org/details/FP106658", site_link="http://waqfeya.com/book.php?bid=11645"),
        BookData(title="ثبت أبي جعفر أحمد بن علي البلوي الوادي آشي (ت: العمراني)",
                 author_name="أبو جعفر أحمد بن علي البلوي الوادي آشي",
                 link="https://archive.org/details/tgaabwatgaabwa",
                 site_link="http://waqfeya.com/book.php?bid=11249"),
        BookData(title="موقع موسوعة صحيح البخاري", author_name="موسوعة صحيح البخاري", link=None,
                 site_link="http://waqfeya.com/book.php?bid=11243")
    ]


@pytest.fixture()
def shamela_bookls1():
    yield [
        BookData(title='فيض الباري على صحيح البخاري', author_name='الكشميري',
                 link='http://d.shamela.ws/epubs/981/98124.epub', site_link='http://shamela.ws/index.php/book/98124'),
        BookData(title='التجريد الصريح لأحاديث الجامع الصحيح', author_name='الزبيدي، زين الدين',
                 link='http://d.shamela.ws/epubs/962/96283.epub', site_link='http://shamela.ws/index.php/book/96283'),
        BookData(title='شرح صحيح البخاري - أسامة سليمان', author_name='أسامة سليمان',
                 link='http://d.shamela.ws/epubs/377/37771.epub', site_link='http://shamela.ws/index.php/book/37771'),
        BookData(title='شرح كتاب الرقاق من صحيح البخاري - المغامسي', author_name='صالح المغامسي',
                 link='http://d.shamela.ws/epubs/377/37732.epub', site_link='http://shamela.ws/index.php/book/37732'),
        BookData(title='شرح كتاب الفتن من صحيح البخاري - عبد الكريم الخضير', author_name='عبد الكريم الخضير',
                 link='http://d.shamela.ws/epubs/217/21741.epub', site_link='http://shamela.ws/index.php/book/21741'),
        BookData(title='شرح صحيح البخاري - عبد الكريم الخضير', author_name='عبد الكريم الخضير',
                 link='http://d.shamela.ws/epubs/217/21724.epub', site_link='http://shamela.ws/index.php/book/21724'),
        BookData(title='شرح القسطلاني = إرشاد الساري لشرح صحيح البخاري', author_name='القسطلاني',
                 link='http://d.shamela.ws/epubs/217/21715.epub', site_link='http://shamela.ws/index.php/book/21715'),
        BookData(title='الحلل الإبريزية من التعليقات البازية على صحيح…', author_name='ابن باز',
                 link='http://d.shamela.ws/epubs/208/20872.epub', site_link='http://shamela.ws/index.php/book/20872'),
        BookData(title='منحة الباري بشرح صحيح البخاري', author_name='الأنصاري، زكريا',
                 link='http://d.shamela.ws/epubs/181/18106.epub', site_link='http://shamela.ws/index.php/book/18106'),
        BookData(title='أعلام الحديث (شرح صحيح البخاري)', author_name='الخطابي',
                 link='http://d.shamela.ws/epubs/169/16946.epub', site_link='http://shamela.ws/index.php/book/16946'),
        BookData(title='شرح كتاب الصوم من صحيح البخاري', author_name='عبد الله بن مانع الروقي',
                 link='http://d.shamela.ws/epubs/145/14539.epub', site_link='http://shamela.ws/index.php/book/14539'),
        BookData(title='كوثر المعاني الدراري في كشف خبايا صحيح البخاري', author_name='محمد الخضر الشنقيطي',
                 link='http://d.shamela.ws/epubs/136/13699.epub', site_link='http://shamela.ws/index.php/book/13699'),
        BookData(title='الكواكب الدراري في شرح صحيح البخاري', author_name='الكرماني، شمس الدين',
                 link='http://d.shamela.ws/epubs/136/13605.epub', site_link='http://shamela.ws/index.php/book/13605'),
        BookData(title='رجال صحيح البخاري = الهداية والإرشاد في معرفة أهل…', author_name='أبو نصر الكلاباذي',
                 link='http://d.shamela.ws/epubs/109/10902.epub', site_link='http://shamela.ws/index.php/book/10902'),
        BookData(title='شرح صحيح البخارى لابن بطال', author_name='ابن بطال',
                 link='http://d.shamela.ws/epubs/104/10486.epub', site_link='http://shamela.ws/index.php/book/10486'),
        BookData(title='منار القاري شرح مختصر صحيح البخاري', author_name='حمزة محمد قاسم',
                 link='http://d.shamela.ws/epubs/097/9794.epub', site_link='http://shamela.ws/index.php/book/9794'),
        BookData(title='شرح كتاب التوحيد من صحيح البخاري', author_name='عبد الله بن محمد الغنيمان',
                 link='http://d.shamela.ws/epubs/096/9610.epub', site_link='http://shamela.ws/index.php/book/9610'),
        BookData(title='عمدة القاري شرح صحيح البخاري', author_name='بدر الدين العيني',
                 link='http://d.shamela.ws/epubs/057/5756.epub', site_link='http://shamela.ws/index.php/book/5756'),
        BookData(title='عشرون حديثا من صحيح البخاري دراسة اسانيدها وشرح…', author_name='عبد المحسن العباد',
                 link='http://d.shamela.ws/epubs/039/3939.epub', site_link='http://shamela.ws/index.php/book/3939'),
        BookData(title='شرح صحيح البخاري للحويني', author_name='أبو إسحق الحويني',
                 link='http://d.shamela.ws/epubs/020/2082.epub', site_link='http://shamela.ws/index.php/book/2082'),
        BookData(title='صحيح البخاري', author_name='البخاري', link='http://d.shamela.ws/epubs/016/1681.epub',
                 site_link='http://shamela.ws/index.php/book/1681'),
        BookData(title='فتح الباري لابن حجر', author_name='ابن حجر العسقلاني',
                 link='http://d.shamela.ws/epubs/016/1673.epub', site_link='http://shamela.ws/index.php/book/1673'),
        BookData(title='تغليق التعليق', author_name='ابن حجر العسقلاني', link='http://d.shamela.ws/epubs/003/347.epub',
                 site_link='http://shamela.ws/index.php/book/347'),
        BookData(title='فتح الباري لابن رجب', author_name='ابن رجب الحنبلي',
                 link='http://d.shamela.ws/epubs/001/137.epub', site_link='http://shamela.ws/index.php/book/137')
    ]


@pytest.fixture()
def shamela_bookls2():
    yield [
        BookData(title='شرح صحيح مسلم - حسن أبو الأشبال', author_name='حسن أبو الأشبال الزهيري',
                 link='http://d.shamela.ws/epubs/370/37026.epub',
                 site_link='http://shamela.ws/index.php/book/37026'),
        BookData(title='عوالي مسلم لابن حجر', author_name='ابن حجر العسقلاني',
                 link='http://d.shamela.ws/epubs/268/26891.epub',
                 site_link='http://shamela.ws/index.php/book/26891'),
        BookData(title='شرح مقدمة صحيح مسلم', author_name='عبد الكريم الخضير',
                 link='http://d.shamela.ws/epubs/237/23737.epub',
                 site_link='http://shamela.ws/index.php/book/23737'),
        BookData(title='شرح كتاب الحج من صحيح مسلم - عبد الكريم الخضير', author_name='عبد الكريم الخضير',
                 link='http://d.shamela.ws/epubs/234/23422.epub',
                 site_link='http://shamela.ws/index.php/book/23422'),
        BookData(title='الكوكب الوهاج شرح صحيح مسلم', author_name='محمد الأمين الهرري',
                 link='http://d.shamela.ws/epubs/182/18268.epub',
                 site_link='http://shamela.ws/index.php/book/18268'),
        BookData(title='مختصر صحيح مسلم للمنذري ت الألباني', author_name='عبد العظيم المنذري',
                 link='http://d.shamela.ws/epubs/176/17616.epub',
                 site_link='http://shamela.ws/index.php/book/17616'),
        BookData(title='فتح المنعم شرح صحيح مسلم', author_name='موسى شاهين لاشين',
                 link='http://d.shamela.ws/epubs/139/13960.epub',
                 site_link='http://shamela.ws/index.php/book/13960'),
        BookData(title='رواية صحيح مسلم من طريق ابن ماهان مقارنة برواية…', author_name='مصدق الدوري',
                 link='http://d.shamela.ws/epubs/135/13554.epub',
                 site_link='http://shamela.ws/index.php/book/13554'),
        BookData(title='إبراهيم بن محمد بن سفيان رواياته وزياداته وتعليقاته…', author_name='عبد الله دمفو',
                 link='http://d.shamela.ws/epubs/121/12158.epub',
                 site_link='http://shamela.ws/index.php/book/12158'),
        BookData(title='علل الأحاديث في صحيح مسلم', author_name='ابن عمار الشهيد',
                 link='http://d.shamela.ws/epubs/060/6049.epub', site_link='http://shamela.ws/index.php/book/6049'),
        BookData(title='صيانة صحيح مسلم', author_name='ابن الصلاح', link='http://d.shamela.ws/epubs/060/6016.epub',
                 site_link='http://shamela.ws/index.php/book/6016'),
        BookData(title='الوقوف على الموقوف', author_name='ابن حجر العسقلاني',
                 link='http://d.shamela.ws/epubs/059/5993.epub', site_link='http://shamela.ws/index.php/book/5993'),
        BookData(title='رجال صحيح مسلم', author_name='ابن مَنْجُويَه',
                 link='http://d.shamela.ws/epubs/058/5860.epub', site_link='http://shamela.ws/index.php/book/5860'),
        BookData(title='المسند المستخرج على صحيح مسلم لأبي نعيم', author_name='أبو نعيم الأصبهاني',
                 link='http://d.shamela.ws/epubs/055/5562.epub', site_link='http://shamela.ws/index.php/book/5562'),
        BookData(title='غرر الفوائد المجموعة', author_name='الرشيد العطار',
                 link='http://d.shamela.ws/epubs/027/2749.epub', site_link='http://shamela.ws/index.php/book/2749'),
        BookData(title='صحيح مسلم', author_name='مسلم', link='http://d.shamela.ws/epubs/017/1727.epub',
                 site_link='http://shamela.ws/index.php/book/1727'),
        BookData(title='شرح السيوطي على مسلم', author_name='السيوطي', link='http://d.shamela.ws/epubs/017/1712.epub',
                 site_link='http://shamela.ws/index.php/book/1712'),
        BookData(title='شرح النووي على مسلم', author_name='النووي', link='http://d.shamela.ws/epubs/017/1711.epub',
                 site_link='http://shamela.ws/index.php/book/1711')
    ]
